#
# Build a CouchDB 1.6.1 Docker.io image
#
FROM shimaore/debian
MAINTAINER Stéphane Alnet <stephane@shimaore.net>

# Install prereqs
RUN apt-get update && apt-get --no-install-recommends -y install \
  build-essential \
  ca-certificates \
  curl \
  erlang-base-hipe \
  erlang-dev \
  erlang-nox \
  git \
  libicu-dev \
  libmozjs185-dev
RUN apt-get --no-install-recommends -y install \
  autoconf \
  m4 \
  libtool \
  automake \
  autoconf-archive \
  pkg-config

# Build couchdb
RUN useradd -m couchdb
USER couchdb
WORKDIR /home/couchdb
RUN git clone http://git-wip-us.apache.org/repos/asf/couchdb.git couchdb.git
# RUN git clone https://github.com/apache/couchdb.git couchdb.git
WORKDIR couchdb.git
RUN git checkout -b build 1.6.1
# Build
RUN ./bootstrap
RUN ./configure --prefix /opt/couchdb
RUN make

# Install
USER root
RUN mkdir -p /opt/couchdb
RUN chown -R couchdb.couchdb /opt/couchdb
USER couchdb
RUN make install
RUN git log > /opt/couchdb/.git.log

# Cleanup source
WORKDIR ..
RUN rm -rf couchdb.git

# Cleanup
USER root
RUN apt-get purge -y \
  build-essential \
  curl \
  git \
  autoconf \
  m4 \
  libtool \
  automake \
  autoconf-archive \
  pkg-config
RUN apt-get autoremove -y
RUN apt-get clean
RUN apt-get autoclean

# Finalize
USER couchdb
EXPOSE 5984
CMD ["/opt/couchdb/bin/couchdb","-n","-A","/opt/couchdb/etc"]
