FROM shimaore/debian
MAINTAINER Stéphane Alnet <stephane@shimaore.net>

# Install prereqs
RUN apt-get update && apt-get --no-install-recommends -y install \
  build-essential \
  ca-certificates \
  curl \
  erlang-dev \
  erlang-nox \
  git \
  libicu-dev \
  libmozjs185-dev
RUN apt-get --no-install-recommends -y install \
  autoconf \
  m4 \
  libtool \
  automake \
  autoconf-archive \
  pkg-config

# Build couchdb
RUN useradd -m couchdb
USER couchdb
WORKDIR /home/couchdb
RUN git clone http://git-wip-us.apache.org/repos/asf/couchdb.git couchdb.git
# RUN git clone https://github.com/apache/couchdb.git couchdb.git
WORKDIR couchdb.git
RUN git checkout -b build 1.6.1
# Build
RUN ./bootstrap
RUN ./configure --prefix /usr/local/couchdb
RUN make

# Install
USER root
RUN make install
RUN git log > /usr/local/couchdb/.git.log
RUN chown -R couchdb.couchdb /usr/local/couchdb/etc/

# Cleanup source
WORKDIR ..
RUN rm -rf couchdb.git

# Cleanup
RUN apt-get purge -y \
  build-essential \
  curl \
  git \
  autoconf \
  m4 \
  libtool \
  automake \
  autoconf-archive \
  pkg-config

RUN apt-get autoremove -y
USER couchdb
EXPOSE 5984
CMD ["/usr/local/couchdb/bin/couchdb","-d"]
